services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jainlakshay
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  lakshay-api:
    container_name: lakshay-api
    image: lakshayyjain/lakshayjain-api
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    command:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customer

  lakshay-react:
    container_name: lakshay-react
    image: lakshayyjain/lakshayjain-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - lakshay-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
